import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AppBar from "@/components/AppBar";
import { appRoutes } from "@/routes/appRoutes";

const inter = Inter({ subsets: ["latin"] });

//Defines the head of the html page
export const metadata: Metadata = {
  title: "Next Training App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Defines the body of the html page */}
      <body className={inter.className}>
        {/* navbar */}
        <div className="container">
          <AppBar title="React" mode="light" routes={appRoutes}/>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
